[package]
name = "jito-shredstream-proxy"
version = "0.1.0"
description = "Receives shreds from Jito, forwarding to local consumers."
authors = ["Jito Team <team@jito.wtf>"]
homepage = "https://jito.wtf/"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
crossbeam-channel = "0.5.5"
env_logger = "0.9.0"
histogram = "0.6.9"
jito-protos = { path = "./jito_protos" }
log = "0.4.14"
prost-types = "0.9.0"
solana-client = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-metrics = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-perf = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-net-utils = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
solana-streamer = { git = "https://github.com/jito-foundation/jito-solana.git", rev = "fdf71bcbb0d962305854884c16335e6c4271b1f2" }
thiserror = "1.0.34"
tokio = "~1.14.1"
tonic = { version = "0.6", features = ["tls", "tls-roots", "tls-webpki-roots"] }
